// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sumula.Data;

#nullable disable

namespace Sumula.Data.Migrations
{
    [DbContext(typeof(SumulaDbContext))]
    partial class SumulaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sumula.Data.Entidades.ArtilheiroEntidade", b =>
                {
                    b.Property<string>("Competicao")
                        .HasColumnType("text")
                        .HasColumnName("competicao");

                    b.Property<int>("Temporada")
                        .HasColumnType("integer")
                        .HasColumnName("temporada");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<int?>("Assistencias")
                        .HasColumnType("integer")
                        .HasColumnName("assistencias");

                    b.Property<int>("Gols")
                        .HasColumnType("integer")
                        .HasColumnName("gols");

                    b.Property<int?>("Jogos")
                        .HasColumnType("integer")
                        .HasColumnName("jogos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("Penaltis")
                        .HasColumnType("integer")
                        .HasColumnName("penaltis");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("time_id");

                    b.HasKey("Competicao", "Temporada", "JogadorId")
                        .HasName("pk_artilheiros");

                    b.ToTable("artilheiros", (string)null);
                });

            modelBuilder.Entity("Sumula.Data.Entidades.ColetaEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Competicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competicao");

                    b.Property<DateTimeOffset>("ExecutadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executada_em");

                    b.Property<int>("PartidasAtualizadas")
                        .HasColumnType("integer")
                        .HasColumnName("partidas_atualizadas");

                    b.Property<int>("Temporada")
                        .HasColumnType("integer")
                        .HasColumnName("temporada");

                    b.HasKey("Id")
                        .HasName("pk_coletas");

                    b.HasIndex("Competicao", "Temporada", "ExecutadaEm")
                        .HasDatabaseName("ix_coletas_competicao_temporada_executada_em");

                    b.ToTable("coletas", (string)null);
                });

            modelBuilder.Entity("Sumula.Data.Entidades.ParticipacaoEntidade", b =>
                {
                    b.Property<string>("Competicao")
                        .HasColumnType("text")
                        .HasColumnName("competicao");

                    b.Property<int>("Temporada")
                        .HasColumnType("integer")
                        .HasColumnName("temporada");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("time_id");

                    b.HasKey("Competicao", "Temporada", "TimeId")
                        .HasName("pk_participacoes");

                    b.HasIndex("TimeId")
                        .HasDatabaseName("ix_participacoes_time_id");

                    b.ToTable("participacoes", (string)null);
                });

            modelBuilder.Entity("Sumula.Data.Entidades.PartidaEntidade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Competicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competicao");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<int?>("GolsMandante")
                        .HasColumnType("integer")
                        .HasColumnName("gols_mandante");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("gols_visitante");

                    b.Property<int>("MandanteId")
                        .HasColumnType("integer")
                        .HasColumnName("mandante_id");

                    b.Property<int>("Rodada")
                        .HasColumnType("integer")
                        .HasColumnName("rodada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Temporada")
                        .HasColumnType("integer")
                        .HasColumnName("temporada");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("visitante_id");

                    b.HasKey("Id")
                        .HasName("pk_partidas");

                    b.HasIndex("MandanteId")
                        .HasDatabaseName("ix_partidas_mandante_id");

                    b.HasIndex("VisitanteId")
                        .HasDatabaseName("ix_partidas_visitante_id");

                    b.HasIndex("Competicao", "Temporada")
                        .HasDatabaseName("ix_partidas_competicao_temporada");

                    b.ToTable("partidas", (string)null);
                });

            modelBuilder.Entity("Sumula.Data.Entidades.TimeEntidade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Escudo")
                        .HasColumnType("text")
                        .HasColumnName("escudo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeCurto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_curto");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_times");

                    b.ToTable("times", (string)null);
                });

            modelBuilder.Entity("Sumula.Data.Entidades.ParticipacaoEntidade", b =>
                {
                    b.HasOne("Sumula.Data.Entidades.TimeEntidade", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participacoes_times_time_id");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Sumula.Data.Entidades.PartidaEntidade", b =>
                {
                    b.HasOne("Sumula.Data.Entidades.TimeEntidade", null)
                        .WithMany()
                        .HasForeignKey("MandanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_times_mandante_id");

                    b.HasOne("Sumula.Data.Entidades.TimeEntidade", null)
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_times_visitante_id");
                });
#pragma warning restore 612, 618
        }
    }
}
