<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Sumula.Core\Sumula.Core.csproj" />
    <ProjectReference Include="..\Sumula.Data\Sumula.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\dados\fotos-jogadores.json" LogicalName="fotos-jogadores.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
